import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier

def train(train_scaled):
    mlflow.set_experiment("Streamlit-Pipeline")

    X_train = train_scaled.drop("species", axis=1)
    y_train = train_scaled["species"]

    with mlflow.start_run() as run:
        model = RandomForestClassifier(criterion= 'gini',max_depth=4)
        model.fit(X_train, y_train)

        # Log and register simultaneously
        mlflow.sklearn.log_model(sk_model=model,
                                 artifact_path="sklearn-model",
                                 registered_model_name="IrisModel")
        return run.info.run_id  #A run_id is just a string generated by MLflow.


